version: '3'

services:
  db:
    image: postgres
    container_name: shopping-cart-database
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
    ports:
      - "5432:5432"
    volumes:
      - .volumes/database-docker:/var/lib/postgresql/data 